# Generated by Django 4.2.6 on 2023-10-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0002_userimage_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
