# Generated by Django 4.2.5 on 2023-11-03 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0004_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
