# Generated by Django 4.2.5 on 2023-11-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0005_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
