# Generated by Django 4.2.5 on 2023-11-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0007_remove_userimage_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='session_key',
        ),
        migrations.AddField(
            model_name='userimage',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
