# Generated by Django 4.2.11 on 2024-03-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0009_image_delete_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
