# Generated by Django 4.2.11 on 2024-03-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0010_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
