# Generated by Django 4.2.11 on 2024-03-24 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0013_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
