# Generated by Django 4.2.11 on 2024-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallabs', '0016_rename_title_experimentsubmission_experiment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsubmission',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
